### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by fred-dedi** [BitBagCommerce/SyliusCmsPlugin#432]
Hi,

I am using your webpack config file in v3.2.2, as described here : https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/v3.2.2/doc/01.1-webpack-config.md

I have the following error on all admin pages : 
        
 ```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at bitbag-page-slug.js:9:1
    at bitbag-page-slug.js:9:1
    at ./vendor/bitbag/cms-plugin/src/Resources/assets/admin/js/bitbag/bitbag-page-slug.js (bitbag-page-slug.js:9:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./vendor/bitbag/cms-plugin/src/Resources/assets/admin/js/bitbag/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./vendor/bitbag/cms-plugin/src/Resources/assets/admin/js/index.js (index.js:3:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./vendor/bitbag/cms-plugin/src/Resources/assets/admin/entry.js (entry.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
(anonymes) @ bitbag-page-slug.js:9
(anonymes) @ bitbag-page-slug.js:9
./vendor/bitbag/cms-plugin/src/Resources/assets/admin/js/bitbag/bitbag-page-slug.js @ bitbag-page-slug.js:9
__webpack_require__ @ bootstrap:19
./vendor/bitbag/cms-plugin/src/Resources/assets/admin/js/bitbag/index.js @ index.js:1
__webpack_require__ @ bootstrap:19
./vendor/bitbag/cms-plugin/src/Resources/assets/admin/js/index.js @ index.js:3
__webpack_require__ @ bootstrap:19
./vendor/bitbag/cms-plugin/src/Resources/assets/admin/entry.js @ entry.js:1
__webpack_require__ @ bootstrap:19
(anonymes) @ bootstrap:83
(anonymes) @ bootstrap:83
```

Maybe i am missing something, but it seems you need to add a babel plugin in your webpack configuration, as babel/polyfill is not working anymore since babel 7 : 

```
.configureBabel((config) => {
    config.plugins.push('@babel/plugin-transform-runtime');
})
```

Thanks

**Comment by pbalcerzak** [comment]
Fixed in #449

**Comment by Geolim4** [comment]
Hello, I'm on 4.0.8 and I still get this error but only since I upgraded to Sylius 1.12.
Ran yarn install and rebuilt my assets, but still pop in my console.

Any idea @pbalcerzak  ?


![Capture d’écran de 2023-11-15 18-16-27](https://github.com/BitBagCommerce/SyliusCmsPlugin/assets/1332071/b3b4be80-32c9-4b77-8ace-0cbaafd670cf)
